// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: game_shelter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameShelterService_AddNewGame_FullMethodName          = "/game_shelter.GameShelterService/AddNewGame"
	GameShelterService_GetUserGames_FullMethodName        = "/game_shelter.GameShelterService/GetUserGames"
	GameShelterService_CreateFriendRequest_FullMethodName = "/game_shelter.GameShelterService/CreateFriendRequest"
)

// GameShelterServiceClient is the client API for GameShelterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameShelterServiceClient interface {
	AddNewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponce, error)
	GetUserGames(ctx context.Context, in *UserGamesRequest, opts ...grpc.CallOption) (*UserGamesResponce, error)
	CreateFriendRequest(ctx context.Context, in *FriendReqRequest, opts ...grpc.CallOption) (*FriendReqResponce, error)
}

type gameShelterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameShelterServiceClient(cc grpc.ClientConnInterface) GameShelterServiceClient {
	return &gameShelterServiceClient{cc}
}

func (c *gameShelterServiceClient) AddNewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*NewGameResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewGameResponce)
	err := c.cc.Invoke(ctx, GameShelterService_AddNewGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameShelterServiceClient) GetUserGames(ctx context.Context, in *UserGamesRequest, opts ...grpc.CallOption) (*UserGamesResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGamesResponce)
	err := c.cc.Invoke(ctx, GameShelterService_GetUserGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameShelterServiceClient) CreateFriendRequest(ctx context.Context, in *FriendReqRequest, opts ...grpc.CallOption) (*FriendReqResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendReqResponce)
	err := c.cc.Invoke(ctx, GameShelterService_CreateFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameShelterServiceServer is the server API for GameShelterService service.
// All implementations must embed UnimplementedGameShelterServiceServer
// for forward compatibility.
type GameShelterServiceServer interface {
	AddNewGame(context.Context, *NewGameRequest) (*NewGameResponce, error)
	GetUserGames(context.Context, *UserGamesRequest) (*UserGamesResponce, error)
	CreateFriendRequest(context.Context, *FriendReqRequest) (*FriendReqResponce, error)
	mustEmbedUnimplementedGameShelterServiceServer()
}

// UnimplementedGameShelterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameShelterServiceServer struct{}

func (UnimplementedGameShelterServiceServer) AddNewGame(context.Context, *NewGameRequest) (*NewGameResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewGame not implemented")
}
func (UnimplementedGameShelterServiceServer) GetUserGames(context.Context, *UserGamesRequest) (*UserGamesResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGames not implemented")
}
func (UnimplementedGameShelterServiceServer) CreateFriendRequest(context.Context, *FriendReqRequest) (*FriendReqResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFriendRequest not implemented")
}
func (UnimplementedGameShelterServiceServer) mustEmbedUnimplementedGameShelterServiceServer() {}
func (UnimplementedGameShelterServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameShelterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameShelterServiceServer will
// result in compilation errors.
type UnsafeGameShelterServiceServer interface {
	mustEmbedUnimplementedGameShelterServiceServer()
}

func RegisterGameShelterServiceServer(s grpc.ServiceRegistrar, srv GameShelterServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameShelterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameShelterService_ServiceDesc, srv)
}

func _GameShelterService_AddNewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameShelterServiceServer).AddNewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameShelterService_AddNewGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameShelterServiceServer).AddNewGame(ctx, req.(*NewGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameShelterService_GetUserGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameShelterServiceServer).GetUserGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameShelterService_GetUserGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameShelterServiceServer).GetUserGames(ctx, req.(*UserGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameShelterService_CreateFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameShelterServiceServer).CreateFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameShelterService_CreateFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameShelterServiceServer).CreateFriendRequest(ctx, req.(*FriendReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameShelterService_ServiceDesc is the grpc.ServiceDesc for GameShelterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameShelterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game_shelter.GameShelterService",
	HandlerType: (*GameShelterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewGame",
			Handler:    _GameShelterService_AddNewGame_Handler,
		},
		{
			MethodName: "GetUserGames",
			Handler:    _GameShelterService_GetUserGames_Handler,
		},
		{
			MethodName: "CreateFriendRequest",
			Handler:    _GameShelterService_CreateFriendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_shelter.proto",
}
