// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: game_shelter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendReqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendReqRequest) Reset() {
	*x = FriendReqRequest{}
	mi := &file_game_shelter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendReqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendReqRequest) ProtoMessage() {}

func (x *FriendReqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendReqRequest.ProtoReflect.Descriptor instead.
func (*FriendReqRequest) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{0}
}

func (x *FriendReqRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *FriendReqRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *FriendReqRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendReqRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FriendReqResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendReqResponce) Reset() {
	*x = FriendReqResponce{}
	mi := &file_game_shelter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendReqResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendReqResponce) ProtoMessage() {}

func (x *FriendReqResponce) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendReqResponce.ProtoReflect.Descriptor instead.
func (*FriendReqResponce) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{1}
}

func (x *FriendReqResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGamesRequest) Reset() {
	*x = UserGamesRequest{}
	mi := &file_game_shelter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGamesRequest) ProtoMessage() {}

func (x *UserGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGamesRequest.ProtoReflect.Descriptor instead.
func (*UserGamesRequest) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{2}
}

func (x *UserGamesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTitle     string                 `protobuf:"bytes,1,opt,name=game_title,json=gameTitle,proto3" json:"game_title,omitempty"`
	GameStatus    string                 `protobuf:"bytes,2,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"`
	GameStore     string                 `protobuf:"bytes,3,opt,name=game_store,json=gameStore,proto3" json:"game_store,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGame) Reset() {
	*x = UserGame{}
	mi := &file_game_shelter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGame) ProtoMessage() {}

func (x *UserGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGame.ProtoReflect.Descriptor instead.
func (*UserGame) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{3}
}

func (x *UserGame) GetGameTitle() string {
	if x != nil {
		return x.GameTitle
	}
	return ""
}

func (x *UserGame) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

func (x *UserGame) GetGameStore() string {
	if x != nil {
		return x.GameStore
	}
	return ""
}

func (x *UserGame) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserGamesResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*UserGame            `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGamesResponce) Reset() {
	*x = UserGamesResponce{}
	mi := &file_game_shelter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGamesResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGamesResponce) ProtoMessage() {}

func (x *UserGamesResponce) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGamesResponce.ProtoReflect.Descriptor instead.
func (*UserGamesResponce) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{4}
}

func (x *UserGamesResponce) GetGames() []*UserGame {
	if x != nil {
		return x.Games
	}
	return nil
}

type NewGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameRequest) Reset() {
	*x = NewGameRequest{}
	mi := &file_game_shelter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameRequest) ProtoMessage() {}

func (x *NewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameRequest.ProtoReflect.Descriptor instead.
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{5}
}

func (x *NewGameRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewGameRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type NewGameResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameResponce) Reset() {
	*x = NewGameResponce{}
	mi := &file_game_shelter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameResponce) ProtoMessage() {}

func (x *NewGameResponce) ProtoReflect() protoreflect.Message {
	mi := &file_game_shelter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameResponce.ProtoReflect.Descriptor instead.
func (*NewGameResponce) Descriptor() ([]byte, []int) {
	return file_game_shelter_proto_rawDescGZIP(), []int{6}
}

func (x *NewGameResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_shelter_proto protoreflect.FileDescriptor

const file_game_shelter_proto_rawDesc = "" +
	"\n" +
	"\x12game_shelter.proto\x12\fgame_shelter\"t\n" +
	"\x10FriendReqRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"-\n" +
	"\x11FriendReqResponce\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x10UserGamesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x88\x01\n" +
	"\bUserGame\x12\x1d\n" +
	"\n" +
	"game_title\x18\x01 \x01(\tR\tgameTitle\x12\x1f\n" +
	"\vgame_status\x18\x02 \x01(\tR\n" +
	"gameStatus\x12\x1d\n" +
	"\n" +
	"game_store\x18\x03 \x01(\tR\tgameStore\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"A\n" +
	"\x11UserGamesResponce\x12,\n" +
	"\x05games\x18\x01 \x03(\v2\x16.game_shelter.UserGameR\x05games\"<\n" +
	"\x0eNewGameRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\"+\n" +
	"\x0fNewGameResponce\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x88\x02\n" +
	"\x12GameShelterService\x12I\n" +
	"\n" +
	"AddNewGame\x12\x1c.game_shelter.NewGameRequest\x1a\x1d.game_shelter.NewGameResponce\x12O\n" +
	"\fGetUserGames\x12\x1e.game_shelter.UserGamesRequest\x1a\x1f.game_shelter.UserGamesResponce\x12V\n" +
	"\x13CreateFriendRequest\x12\x1e.game_shelter.FriendReqRequest\x1a\x1f.game_shelter.FriendReqResponceB'Z%github.com/Hordevcom/GameShelf/pkg/pbb\x06proto3"

var (
	file_game_shelter_proto_rawDescOnce sync.Once
	file_game_shelter_proto_rawDescData []byte
)

func file_game_shelter_proto_rawDescGZIP() []byte {
	file_game_shelter_proto_rawDescOnce.Do(func() {
		file_game_shelter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_shelter_proto_rawDesc), len(file_game_shelter_proto_rawDesc)))
	})
	return file_game_shelter_proto_rawDescData
}

var file_game_shelter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_shelter_proto_goTypes = []any{
	(*FriendReqRequest)(nil),  // 0: game_shelter.FriendReqRequest
	(*FriendReqResponce)(nil), // 1: game_shelter.FriendReqResponce
	(*UserGamesRequest)(nil),  // 2: game_shelter.UserGamesRequest
	(*UserGame)(nil),          // 3: game_shelter.UserGame
	(*UserGamesResponce)(nil), // 4: game_shelter.UserGamesResponce
	(*NewGameRequest)(nil),    // 5: game_shelter.NewGameRequest
	(*NewGameResponce)(nil),   // 6: game_shelter.NewGameResponce
}
var file_game_shelter_proto_depIdxs = []int32{
	3, // 0: game_shelter.UserGamesResponce.games:type_name -> game_shelter.UserGame
	5, // 1: game_shelter.GameShelterService.AddNewGame:input_type -> game_shelter.NewGameRequest
	2, // 2: game_shelter.GameShelterService.GetUserGames:input_type -> game_shelter.UserGamesRequest
	0, // 3: game_shelter.GameShelterService.CreateFriendRequest:input_type -> game_shelter.FriendReqRequest
	6, // 4: game_shelter.GameShelterService.AddNewGame:output_type -> game_shelter.NewGameResponce
	4, // 5: game_shelter.GameShelterService.GetUserGames:output_type -> game_shelter.UserGamesResponce
	1, // 6: game_shelter.GameShelterService.CreateFriendRequest:output_type -> game_shelter.FriendReqResponce
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_shelter_proto_init() }
func file_game_shelter_proto_init() {
	if File_game_shelter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_shelter_proto_rawDesc), len(file_game_shelter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_shelter_proto_goTypes,
		DependencyIndexes: file_game_shelter_proto_depIdxs,
		MessageInfos:      file_game_shelter_proto_msgTypes,
	}.Build()
	File_game_shelter_proto = out.File
	file_game_shelter_proto_goTypes = nil
	file_game_shelter_proto_depIdxs = nil
}
